name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pages: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4  # ✅ Latest version

      - name: Cache APT Packages (Fix for stale dependencies)
        uses: awalsh128/cache-apt-pkgs-action@v1.4.3  # ✅ Fix caching issues
        with:
          packages: "curl git"

      - name: Set up Node.js
        uses: actions/setup-node@v4  # ✅ Latest version
        with:
          node-version: 18  # Use a compatible Node.js version

      - name: Inject Hugging Face Token
        env:
          HF_AUTH_TOKEN: ${{ secrets.HF_AUTH_TOKEN }}
        run: |
          npm install fs path
          node scripts/inject-token.js

      # Debugging Step: Check if the `_site` directory exists before upload
      - name: Debug: Check _site directory
        run: ls -R _site || echo "❌ ERROR: _site directory not found!"

      - name: Upload GitHub Pages Artifact  # ✅ Use correct action for Pages
        uses: actions/upload-pages-artifact@v1  # ✅ Should be `v1`
        with:
          path: _site  # Ensure `_site` exists

      - name: Deploy Artifact
        uses: actions/deploy-pages@v2  # ✅ Deploy using correct action
