name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Runs on every push to the `main` branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pages: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4  # ✅ Latest version

      - name: Cache APT Packages (Fix for stale dependencies)
        uses: awalsh128/cache-apt-pkgs-action@v1.4.3  # ✅ Fix caching issues
        with:
          packages: "curl git"

      - name: Set up Node.js
        uses: actions/setup-node@v4  # ✅ Latest version
        with:
          node-version: 18  # Updated for better compatibility

      - name: Inject Hugging Face Token
        env:
          HF_AUTH_TOKEN: ${{ secrets.HF_AUTH_TOKEN }}
        run: |
          npm install fs path
          node scripts/inject-token.js

      - name: Build Static Site
        run: |
          mkdir -p _site
          find . -maxdepth 1 -not -name "_site" -not -name "." -exec cp -r {} _site/ \;

      # ✅ Debugging Step: Ensure `_site` exists before uploading
      - name: Debug: Check _site directory
        run: |
          echo "Listing _site directory contents:"
          ls -la _site || echo "_site directory NOT FOUND"

      # ✅ Upload the artifact with the correct name
      - name: Upload GitHub Pages Artifact
        uses: actions/upload-pages-artifact@v2  # ✅ Latest version
        with:
          path: _site  # ✅ Ensure path exists

      # ✅ Deploy the uploaded artifact
      - name: Deploy Artifact
        uses: actions/deploy-pages@v2  # ✅ Latest version
